# Generated by Django 3.2.5 on 2021-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('course_trainer', models.CharField(max_length=35)),
                ('course_code', models.CharField(max_length=10)),
                ('course_description', models.TextField(max_length=200)),
                ('notes', models.FileField(upload_to='Documents')),
                ('course_structure', models.FileField(upload_to='Documents')),
            ],
        ),
    ]
