# Generated by Django 3.2.8 on 2021-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
