# Generated by Django 3.2.8 on 2021-10-14 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
