# Generated by Django 3.2.5 on 2021-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Rwandan', 'Rwandan'), ('Ugandan', 'Ugandan'), ('South Sudaneese', 'South Sudaneese')], default='Kenyan', max_length=15)),
                ('class_name', models.CharField(blank=True, choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], default='AnitaB', max_length=15, null=True)),
                ('id_number', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('medical_report', models.FileField(upload_to='documents/')),
                ('guardian_name', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
